version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root@1234
      MYSQL_DATABASE: students
      MYSQL_USER: hedi
      MYSQL_PASSWORD: root@1234
    volumes:
      - mysql_data:/var/lib/mysql

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: spring_boot_app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/students
#      SPRING_DATASOURCE_USERNAME: hedi
#      SPRING_DATASOURCE_PASSWORD: root@1234

volumes:
  mysql_data:
